spring.application.name=LegacyDoc AI

spring.ai.ollama.base-url=http://localhost:11431
spring.ai.ollama.chat.model=gemma3:4b-it-q4_K_M
spring.ai.ollama.embedding.model=mxbai-embed-large

spring.datasource.url=jdbc:postgresql://localhost:5433/ragdb
spring.datasource.username=postgres
spring.datasource.password=admin

#spring.ai.ollama.embedding.options.num-ctx=8192