spring.application.name=LegacyDoc AI

spring.ai.ollama.base-url=http://localhost:11431
spring.ai.ollama.chat.model=gemma3:4b-it-q4_K_M


spring.datasource.url=jdbc:postgresql://localhost:5433/ragdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.main.allow-circular-references=true
logging.level.org.springframework.beans.factory=DEBUG
logging.level.org.springframework.context=DEBUG